CREATE TABLE IF NOT EXISTS users (
	cpf VARCHAR(15) PRIMARY KEY,
	name VARCHAR (200) NOT NULL,
	email VARCHAR (200) NOT NULL,
	password VARCHAR (200) NOT NULL,
	created_at TIMESTAMP NOT NULL 
);


CREATE TABLE IF NOT EXISTS servers (
	id INT PRIMARY KEY,
	name VARCHAR (50) NOT NULL,
	created_at TIMESTAMP NOT NULL 
);
